Feature/pokemonlist
belgoscode/InnowisePokemons pull request #1
Opened 2024-06-16 20:12 UTC by belgoscode

## Результат
![screenshots](https://github.com/belgoscode/InnowisePokemons/assets/133965870/1d1b57b4-0083-405d-9b82-51be93a07fe1)
](url)

2024-06-16 20:17 UTC, pzinkevich42innowise commented on .idea/deploymentTargetSelector.xml
Это минус сразу

2024-06-16 20:22 UTC, pzinkevich42innowise requested changes

2024-06-16 20:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/innowisepokemons/DetailedInfoActivity.kt
> +        heightTextView = findViewById(R.id.pokemon_height)
биндинг?

2024-06-16 20:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/innowisepokemons/DetailedInfoActivity.kt
> +        nameTextView.text = pokemon?.name
А если null?

2024-06-16 20:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/innowisepokemons/MainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, pokemonNames)
Вроде разобрались как без ListView обойтись, но ок

2024-06-16 20:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/innowisepokemons/PokemonList.kt
> +    val pokemons: List<Pokemon> = listOf(
Может mapOf?

2024-06-16 21:43 UTC, belgoscode commented on .idea/deploymentTargetSelector.xml
Удалил /.idea из репозитория, добавил ./idea/* в глобальный gitignore (я добавлял не в тот 🙃)

2024-06-16 21:44 UTC, belgoscode commented on app/src/main/java/com/example/innowisepokemons/DetailedInfoActivity.kt
> +        heightTextView = findViewById(R.id.pokemon_height)
Накосячил и не заметил. Исправил.

2024-06-16 21:44 UTC, belgoscode commented on app/src/main/java/com/example/innowisepokemons/PokemonList.kt
> +    val pokemons: List<Pokemon> = listOf(
Исправил

2024-06-17 06:32 UTC, pzinkevich42innowise requested changes
Надо доработать

2024-06-17 09:37 UTC, belgoscode commented on app/src/main/java/com/example/innowisepokemons/DetailedInfoActivity.kt
> +        binding.pokemonName.text = pokemon?.name
Добавил проверки

2024-06-17 11:35 UTC, pzinkevich42innowise approved these changes

2024-06-19 13:33 UTC, merged